version: "3.9"
services:
  web:
    build: .
    container_name: web
    ports:
      - "8080:8080"
    links: 
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5

    restart: on-failure
  
  redis:
    image: redis
    container_name: redis
